
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  application:
    name: poop-api
  datasource:
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5432/COCOMPETE
  jpa:
    show-sql: true

